
# Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
plugins=(
git #ga (git add) gb (git branch) etc
osx #spotify man-preview show/hidefiles ofd (open Finder d) and cdf (cd Finder)
)
source $ZSH/oh-my-zsh.sh

#ls colors
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# Powerline Shell
function powerline_precmd() {
PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
for s in "${precmd_functions[@]}"; do
	if [ "$s" = "powerline_precmd" ]; then
		return
	fi
done
precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
	install_powerline_precmd
fi

# Aliases
alias gcc='gcc-8'
alias cc='gcc-8'
alias g++='g++-8'
alias c++='g++-8'

alias py='python3'
alias python='python3'
alias emu5x= '~/Library/Android/sdk/tools/emulator @Nexus_5X_API_28_x86'

# Windows Linux Subsystem Specific
if [ `echo $PATH | grep -c "Windows" ` -gt 0 ]
then
	export DISPLAY=:0
	export BROWSER=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe
fi

# nvm
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# android sdk
export ANDROID_HOME="$HOME/Library/Android/sdk/"
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"

# fastlane
export PATH="$PATH:$HOME/.fastlane/bin"
